# basic options
title: John's blog page
author: John Boniello
email: johnboniello@gmail.com
description: My blog page
twitter_username: johnboniello
github_username:  johnboniello
google_analytics: UA-115065150-2
# Build settings
markdown: kramdown
theme: minima
